const { resolve } = require("path");

const swaggerAutogen = require('swagger-autogen')();

const docs = {
    info: {
        version: "1.0.0",
        title: "Puzzle Website API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: `localhost:${process.env.PORT}`,
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json']
}

const outputFile = "./src/swagger_output.json";
const apis = [resolve(__dirname, "./api/*.route.js")];

swaggerAutogen(outputFile, apis, docs);
